[[plugins]]
# Cool status line
repo = 'itchyny/lightline.vim'

[[plugins]]
# Useful explore
repo = 'scrooloose/nerdtree'

[[plugins]]
# Show class, function, etc...
repo = 'majutsushi/tagbar'

[[plugins]]
# Asynchronous execution of commands
repo  = 'Shougo/vimproc.vim'
build = 'make'


