[[plugins]]
# Cool status line
repo = 'itchyny/lightline.vim'
# When add plug-in, load a configuration file
hook_add = "source $VIM_ROOT/config/lightline.vim"

[[plugins]]
# Useful explore
repo = 'scrooloose/nerdtree'
hook_add = "source $VIM_ROOT/config/nerdtree.vim"

[[plugins]]
# Show class, function, etc...
repo = 'majutsushi/tagbar'
hook_add = "source $VIM_ROOT/config/tagbar.vim"

[[plugins]]
# Show search status
# ex) word (now / max)
repo = 'osyo-manga/vim-anzu'
hook_add = "source $VIM_ROOT/config/anzu.vim"

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
# Show indent guides
repo = 'nathanaelkane/vim-indent-guides'
hook_add = "source $VIM_ROOT/config/indent-guides.vim"

[[plugins]]
# gf command customizer
repo = 'kana/vim-gf-user'
hook_add = "source $VIM_ROOT/config/gf-user.vim"
