[[plugins]]
# Intellisense
repo = 'Shougo/neocomplete.vim'
on_i = 1 # Read into INSERT MODE

[[plugins]]
# Show search status
# ex) word (now / max)
repo = 'osyo-manga/vim-anzu'

[[plugins]]
# for Unite file_mru
repo      = 'Shougo/neomru.vim'
on_source = ['unite.vim'] # Load when load unite.vim
