[[plugins]]
# Intellisense
repo = 'Shougo/neocomplete.vim'
if = 'has("lua")'
on_event = "InsertEnter"
hook_source = "source $VIM_ROOT/config/neocomplete.vim"

[[plugins]]
# for Unite file_mru
repo      = 'Shougo/neomru.vim'
# When load unite.vim, load plug-in
on_source = ['unite.vim']

[[plugins]]
# Asynchronous execution of commands
repo  = 'Shougo/vimproc.vim'
build = 'make' # auto build
on_source = ['unite.vim']

[[plugins]]
# Unified interface
repo = 'Shougo/unite.vim'
depends = 'neomru.vim'
hook_source= "source $VIM_ROOT/config/unite.vim"

