[[plugins]]
# Intellisense
repo = 'Shougo/neocomplete.vim'
if = 'has("lua")'
on_i = 1 # Load when enter INSERT MODE
hook_source = "source $VIM_ROOT/config/neocomplete.vim"

[[plugins]]
# Show search status
# ex) word (now / max)
repo = 'osyo-manga/vim-anzu'
on_cmd = ['/', '?'] # Load when find command
hook_source = "source $VIM_ROOT/config/anzu.vim"

[[plugins]]
# for Unite file_mru
repo      = 'Shougo/neomru.vim'
on_source = ['unite.vim'] # Load when load unite.vim
